# Generated by Django 4.1.3 on 2022-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=512, verbose_name="Отдел")),
                ("spots", models.IntegerField(verbose_name="Вместимость")),
            ],
            options={
                "verbose_name": "Комнаты",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Имя")),
                ("paycheck", models.IntegerField(verbose_name="Зарплата")),
                (
                    "date_joined",
                    models.DateField(verbose_name="Дата поступления на работу"),
                ),
            ],
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
